name: Python Unittest CommuniAPI

on: [ push, pull_request ]

env:
  CT_TOKEN: ${{ secrets.CT_TOKEN }}
  CT_DOMAIN: ${{ vars.CT_DOMAIN }}
  COMMUNI_TOKEN: ${{secrets.COMMUNI_TOKEN}}
  COMMUNI_SERVER: ${{vars.COMMUNI_SERVER}}
  COMMUNI_APPID: ${{secrets.COMMUNI_APPID}}

jobs:
  list-domain:
    runs-on: ubuntu-latest
    environment: ev_kirche_baiersbronn
    steps:
      - name: show CT_DOMAIN for this job
        run: echo $CT_DOMAIN
  test:
    runs-on: ubuntu-latest
    environment: ev_kirche_baiersbronn
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install --no-cache-dir -r docker/requirements.txt

      - name: Run unittests
        run: |
          python -m unittest TestCommuniApp